spec: add Makefile & spec
C2Devel/pytest-asyncio pull request #3
Opened 2020-12-15 16:48 UTC by Sharpeye90

2020-12-21 15:04 UTC, odivlad commented on Makefile
> +	@rm -rf build dist $(PROGRAM).egg-info $(PROGRAM)-*.tar.gz *.egg *.src.rpm
Newline на конце добавь, пож.

2020-12-21 15:44 UTC, odivlad commented on python-pytest-asyncio.spec
> +BuildRequires:  python36-devel
Это, наверное, стоит заменить на `%{python3_pkgversion}`, чтобы корректно собиралось для centos > 7.5, если и его не прикроют...

2020-12-21 15:49 UTC, odivlad commented on setup.py
> +    author="Tin Tvrtkovic",
А зачем это изменение?

2020-12-22 08:23 UTC, Sharpeye90 commented on setup.py
> +    author="Tin Tvrtkovic",
наш коджи не смог обработать символ ć - поругалась на ascii, я решил что могу в этом случае быстро поменять проблемный символ

2021-01-11 22:34 UTC, odivlad requested changes

2021-01-11 22:34 UTC, odivlad commented on python-pytest-asyncio.spec
> +BuildRequires:  python%{python3_pkgversion}-pytest >= 3.0.6
Тут не 3.0.7?

2021-01-11 22:34 UTC, odivlad commented on python-pytest-asyncio.spec
> +Requires:       python%{python3_pkgversion}-pytest >= 3.0.6
и тут

2021-01-11 22:34 UTC, odivlad commented on setup.py
> +    author="Tin Tvrtkovic",
Давай тогда это отдельным коммитом, это все же не относится к самой спеке.

2021-01-11 22:34 UTC, odivlad commented on python-pytest-asyncio.spec
> +Name:           python36-%{pypi_name}
в epel пакет называется `python3-pytest-asyncio`, почему ты решил его изменить?

2021-01-12 08:51 UTC, Sharpeye90 commented on python-pytest-asyncio.spec
> +Name:           python36-%{pypi_name}
Потому что в gear указали python36-pytest-asyncio, решил поправить сам тут, а не возвращать Диме PR в c2

2021-01-12 09:01 UTC, odivlad commented on python-pytest-asyncio.spec
> +Name:           python36-%{pypi_name}
`%python_provide` сделает свое дело. можно смело править

2021-01-13 09:27 UTC, odivlad approved these changes

2021-01-13 09:30 UTC, merged